Update GRUB to 2.06-13+deb12u1
endlessm/grub pull request #90
Opened 2023-12-07 10:23 UTC by starnight

Rebase on upstream grub 2.06 and applied debian patches with [DEB] prefix, first.

And, here is the list of downstream commits https://github.com/endlessm/grub/compare/a3e9e1f9cdfb63750c71ea72a1e8dfa1db94853e...T35062:
## Add:
* [x] 8dce43644 gettext: Use grub.d.sed script from source directory
* [x] 230769f16 Make autogen.sh skip "_obsbuild"
* [x] ff6005ddb po: Drop 2nd insert-header.sin to avoid permission deny
## Drop:
* [ ] 32ed66abb [ENDLESS] break verifiers to stop boot failures READ LOG WHEN REBASING
## Upstream has -> Drop:
* [ ] 8c7728f16 commands/file: Fix array/enum desync
* [ ] e6ece3e2f minix: avoid mistakenly probing ext2 filesystems
## Picked
* [x] 37d01bec5 blscfg: always boot from $root
## Drop!  No more failing:
* [ ] 7bd1ed10c Skip failing tests:
## Picked
* [x] 32fbab169 Handle gnulib submodule
## Fixed conflict
* [x] 095fe0d54 linux: tweak linuxefi handoff behaviour
* [x] b6708e1c7 grub: Do not read list files when secure-boot is enabled
## Upstream has corresponding modification -> Drop
* [ ] e63a2f7a8 EFI: console: Do not set text-mode until we actually need it
## Picked
* [x] 7795a4e11 grub-mkconfig: Do not allow grub.conf change on ostree systems
* [x] 3896e36b7 Disable cbfs module
* [x] 8c59ed8d8 search: add optional --quiet parameter
* [x] f4f1e70db probe: Add a 'bootable' option
* [x] 0e83d955b hexdump: Add export to variable
* [x] 149fec5bc env: Export bootdev
* [x] 85aded587 search: Add search by filesystem type
* [x] d3c47c261 grub-install: Add support for embedded configuration
* [x] fd8a761e9 Clean ChangeLog for distcheck
* [x] dd1d3fe56 Automatically run configure from autogen.sh
* [x] b55e0d4c0 blscfg: add "savedefault" to generic Endless entry
* [x] bf2fbe4b4 blscfg: adjust boot device to match Endless' layout
* [x] b0db2c1ca blscfg: Show only one entry for Endless
* [x] b5c4fccd1 blscfg: Add initramfs-append to the initrd command line if it exists
* [x] 66d271b92 blscfg: Introduce 'kparams' env to add custom bootargs
* [x] 615715501 blscfg: Dynamically prepend root= parameter
* [x] 000a72860 blscfg: sort BLS entries by 'version' field
* [x] 478fadb12 blscfg: Add support for the devicetree field
* [x] b96d13074 blscfg: add const qualifiers to fix compile
* [x] d11be373d blscfg: add blscfg module to parse Boot Loader Specification snippets

https://phabricator.endlessm.com/T35062

2023-12-11 19:56 UTC, dbnicholson commented
> Rebase on upstream grub 2.06 and applied debian patches with [DEB] prefix, first.
> 
> * [x]  [230769f](https://github.com/endlessm/grub/commit/230769f168ea7f3021ec3971e6dd3bd99f8c61d6) Make autogen.sh skip "_obsbuild"

This is not going to be enough. It already [failed](https://ci.endlessos.org/job/obs-grub-master-pr/35/) when triggered on Jenkins for a second time because it's not starting from a pristine checkout. It finds the generated `ascii.h` and fails because that's not included in files to distributed.

That's why I changed it to [use `git ls-files`](https://github.com/endlessm/grub/commit/1dfd9d463de3caf55706f426897b825573b47e63) in my branch.

> ## Drop:
> * [ ]  [32ed66a](https://github.com/endlessm/grub/commit/32ed66abb419d926c182bdafbbc783676f4841fe) [ENDLESS] break verifiers to stop boot failures READ LOG WHEN REBASING

Did you confirm this can be dropped? From what I can tell, the old patches and https://phabricator.endlessm.com/T31671 point to how `grub_shim_lock_verifier_setup` was skipped since the whole verifier setup was missing. However, the current patches do not skip `grub_shim_lock_verifier_setup`, so probably Debian is using the `shim_lock` secure boot verification like upstream.

> * [x]  [dd1d3fe](https://github.com/endlessm/grub/commit/dd1d3fe56c256d7de3a8b320836b7768575b88d5) Automatically run configure from autogen.sh

You can drop this. It doesn't do anything useful anymore.

> * [x]  [b55e0d4](https://github.com/endlessm/grub/commit/b55e0d4c0c034231e38ee257eab6580bc6782548) blscfg: add "savedefault" to generic Endless entry

Sad that `blscfg` is still entirely downstream. I even checked grub's `master` branch and there's no such thing.

2023-12-11 23:13 UTC, dbnicholson requested changes
I _think_ this is mostly going to work, but at least the silly `POTFILES` thing will need a little more work.

2023-12-12 10:37 UTC, starnight commented
Thanks for the review!

> > Rebase on upstream grub 2.06 and applied debian patches with [DEB] prefix, first.
> > 
> > * [x]   [230769f](https://github.com/endlessm/grub/commit/230769f168ea7f3021ec3971e6dd3bd99f8c61d6) Make autogen.sh skip "_obsbuild"
> 
> This is not going to be enough. It already [failed](https://ci.endlessos.org/job/obs-grub-master-pr/35/) when triggered on Jenkins for a second time because it's not starting from a pristine checkout. It finds the generated `ascii.h` and fails because that's not included in files to distributed.
> 
> That's why I changed it to [use `git ls-files`](https://github.com/endlessm/grub/commit/1dfd9d463de3caf55706f426897b825573b47e63) in my branch.

Replace commit `Make autogen.sh skip "_obsbuild"` with the commit `autogen: Make POTFILES.in generation reproducible`.
 
> > ## Drop:
> > 
> > * [ ]   [32ed66a](https://github.com/endlessm/grub/commit/32ed66abb419d926c182bdafbbc783676f4841fe) [ENDLESS] break verifiers to stop boot failures READ LOG WHEN REBASING
> 
> Did you confirm this can be dropped? From what I can tell, the old patches and https://phabricator.endlessm.com/T31671 point to how `grub_shim_lock_verifier_setup` was skipped since the whole verifier setup was missing. However, the current patches do not skip `grub_shim_lock_verifier_setup`, so probably Debian is using the `shim_lock` secure boot verification like upstream.

Debian's changelog mentioned:
```
grub2 (2.06-1) unstable; urgency=medium

  * Use "command -v" in maintainer scripts rather than "which".
  * New upstream release.
    - Switch to the upstream shim_lock verifier, dropping several more
      manual checks for UEFI Secure Boot.
...
```
So, yes.  Debian uses upstream's `shim_lock` secure boot verification now.

> > * [x]   [dd1d3fe](https://github.com/endlessm/grub/commit/dd1d3fe56c256d7de3a8b320836b7768575b88d5) Automatically run configure from autogen.sh
> 
> You can drop this. It doesn't do anything useful anymore.

Ok!  And, tested & dropped.

2023-12-12 21:59 UTC, dbnicholson approved these changes

2023-12-12 22:00 UTC, merged